### ISSUE TITLE
npm 安装后启动失败

### ISSUE THREAD

**Issue by harryhappy** [Serverless-Devs/s-cli#3]
npm  -v 后报错

/usr/lib/node_modules/@serverless-devs/s/node_modules/chalk/source/index.js:106
        ...styles,
        ^^^      

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@serverless-devs/s/node_modules/inquirer/lib/objects/separator.js:2:13)
----
node -v 
v6.17.1

**Comment by harryhappy** [comment]
java 和 golang开发者  对node不是很熟

**Comment by anycodes** [comment]
感谢大佬的支持。

通常情况下，您可以通过node的官网或得到安装方法，这里建议您安装node 10+

您可以在这里下载相对应版本的[Nodejs](http://nodejs.cn/download/)

您也可以参考这个[安装文档](http://nodejs.cn/learn/how-to-install-nodejs)

最后，如果还是无法安装，您可以联系我的钉钉：3ga_y0qsmdx5y

也可以给我发邮件，我加您好友，让我们的小伙伴，1-1的支持。

**Comment by harryhappy** [comment]
升级到12.19.0  OK了  感谢
